'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NOIApplication

    '''<summary>
    '''lblNOIHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfNOISubmissionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNOISubmissionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfIsLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIsLocked As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSiteInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSiteInfo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTaxParcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTaxParcel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPiTypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPiTypeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''wzNOI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wzNOI As Global.System.Web.UI.WebControls.Wizard

    '''<summary>
    '''wsApplicantInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wsApplicantInfo As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''ucnaOwnerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaOwnerInfo As Global.NoticeOfIntent.ucNameAddressInfo

    '''<summary>
    '''lblContactInfoHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactInfoHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCopyContactInfoFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCopyContactInfoFrom As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCopyContactInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyContactInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ucnaContactInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaContactInfo As Global.NoticeOfIntent.ucNameAddressInfo

    '''<summary>
    '''divBilleeDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBilleeDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlCopyBilleeInfoFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCopyBilleeInfoFrom As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCopyBilleeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCopyBilleeInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ucnaBilleeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaBilleeInfo As Global.NoticeOfIntent.ucNameAddressInfo

    '''<summary>
    '''wsProjectInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wsProjectInfo As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''lblSiteInfoPnlHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteInfoPnlHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucnaSiteInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaSiteInfo As Global.NoticeOfIntent.ucNameAddressInfo

    '''<summary>
    '''divProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProjectType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProjectType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtProjectTypeOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectTypeOther As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvProjectTypeOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProjectTypeOther As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''divTaxParcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTaxParcel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvTaxparcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvTaxparcel As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''cvTaxparcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvTaxparcel As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''divLocDet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocDet As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLatitude As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CompareValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''rfvLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLatitude As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hfX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfX As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLongitude As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CompareValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator2 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''rfvLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvLongitude As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revLongitude As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''hfY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfY As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtWatershed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWatershed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvWatershed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvWatershed As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''hfWaterShedCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfWaterShedCode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''divbmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divbmp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvSWBMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvSWBMP As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''wsProjectInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wsProjectInfo1 As Global.System.Web.UI.WebControls.WizardStep

    '''<summary>
    '''divOtherInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOtherInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rblSWPPPYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSWPPPYesNo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvSWPPPYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSWPPPYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvSWPPPYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSWPPPYesNo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblPlanApprovalAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlanApprovalAgency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPlanApprovalAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPlanApprovalAgency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvPlanApprovalAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPlanApprovalAgency As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAreaOfSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAreaOfSite As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotalAreaOfSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAreaOfSite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTotalAreaOfSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTotalAreaOfSite As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''covtxtTotalAreaOfSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents covtxtTotalAreaOfSite As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lblAreaOfDisturbed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAreaOfDisturbed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAreaOfDisturbed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaOfDisturbed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvAreaOfDisturbed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAreaOfDisturbed As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''covtxtAreaofDisturbed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents covtxtAreaofDisturbed As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lblConstructStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConstructStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConstructStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstructStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvConstructStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvConstructStartDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblConstructCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConstructCompleteDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConstructCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstructCompleteDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvConstructCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvConstructCompleteDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvConstructCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvConstructCompleteDate As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''divSicCodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSicCodes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvSIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvSIC As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''divNAICSCodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNAICSCodes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvNAICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvNAICS As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''divNoExposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoExposure As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkDisableNoExposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisableNoExposure As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lvNoExposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvNoExposure As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''cvNoExposure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvNoExposure As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''divOutfall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOutfall As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvOutfall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvOutfall As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''hfOutfalllist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOutfalllist As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''divPesticidesEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPesticidesEntity As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rblEntityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblEntityType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvrblEntityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvrblEntityType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblCommercialApplicatorID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommercialApplicatorID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCommercialApplicatorID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommercialApplicatorID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divPesticidesThreshold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPesticidesThreshold As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkInsectPestControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInsectPestControl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWeedPestControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWeedPestControl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAnimalPestControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAnimalPestControl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkForestCanopyPestControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkForestCanopyPestControl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rbtnThresholdNotExceeded control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnThresholdNotExceeded As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''cvAnnlTreatmentThreshold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvAnnlTreatmentThreshold As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''divChemicals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChemicals As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvAPChemicals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvAPChemicals As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
End Class
