'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NOIDocs

    '''<summary>
    '''lblFileDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFileDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFileDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rvtxtFileDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvtxtFileDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''fileupload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileupload As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblFileSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfMaxlength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMaxlength As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUploadFiles As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hlUploadFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlUploadFiles As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cvFileUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvFileUpload As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lvUploadedFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvUploadedFiles As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''cvCheckDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvCheckDocument As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnContinue As Global.System.Web.UI.WebControls.Button
End Class
