'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NOTCoPermittee

    '''<summary>
    '''lblNOIID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNOIIDDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIIDDisplay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfNOISubmissionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNOISubmissionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblNOIDateReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIDateReceived As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNOIDateReceivedDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIDateReceivedDisplay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucnaProjectDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaProjectDetails As Global.NoticeOfIntent.ucNameAddressInfoReadOnly

    '''<summary>
    '''lblCoPermitteeAppRecdDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoPermitteeAppRecdDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCoPermitteeAppRecDateDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoPermitteeAppRecDateDisplay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucnaCoPermitteeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaCoPermitteeInfo As Global.NoticeOfIntent.ucNameAddressInfoReadOnly

    '''<summary>
    '''txtCompletionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompletionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCompletionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCompletionDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblStatisfiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblStatisfiedYesNo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvSatisfiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSatisfiedYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvSatisfiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSatisfiedYesNo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rblVerifiedYesNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVerifiedYesNO As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvVerifiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvVerifiedYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvVerifiedYesNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvVerifiedYesNO As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rblAchievedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAchievedYesNo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvAchievedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAchievedYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvAchievedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvAchievedYesNo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
