'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NOTGeneralPermit

    '''<summary>
    '''lblNOIHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFacHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNOIID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNOIIDDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIIDDisplay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfNOISubmissionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNOISubmissionID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblNOIDateReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIDateReceived As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNOIDateReceivedDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIDateReceivedDisplay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucnaProjectDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaProjectDetails As Global.NoticeOfIntent.ucNameAddressInfoReadOnly

    '''<summary>
    '''divLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lvTaxparcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvTaxparcel As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''divLocation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocation1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLatitude As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLongitude As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContactHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ucnaOriPermitteeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaOriPermitteeInfo As Global.NoticeOfIntent.ucNameAddressInfoReadOnly

    '''<summary>
    '''divTerminationForCSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTerminationForCSS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCompletionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompletionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvCompletionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCompletionDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rblStatisfiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblStatisfiedYesNo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvSatisfiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSatisfiedYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvSatisfiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvSatisfiedYesNo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rblVerifiedYesNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVerifiedYesNO As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvVerifiedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvVerifiedYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvVerifiedYesNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvVerifiedYesNO As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''rblAchievedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAchievedYesNo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rfvAchievedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAchievedYesNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cvAchievedYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvAchievedYesNo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''divTerminationForISAndAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTerminationForISAndAP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkOpTransferred control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpTransferred As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNoDischargeAssociated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNoDischargeAssociated As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCoveredNPDESPermit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCoveredNPDESPermit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cvTerReasonForISAndAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvTerReasonForISAndAP As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
