'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucTaxParcelAdd

    '''<summary>
    '''lblSelectCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectCounty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbNewCastle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNewCastle As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbKent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbKent As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbSussex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSussex As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblTPNCNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTPNCNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTPNC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPNC1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPNC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPNC2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPNC3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPNC3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPNC4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPNC4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTPKentNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTPKentNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTaxKentHundred control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTaxKentHundred As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKentCommunityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKentCommunityCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtKentTP3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTPSussexNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTPSussexNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTPSussex1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex6 As Global.System.Web.UI.WebControls.TextBox
End Class
