'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucTaxParcelKent

    '''<summary>
    '''ddlTaxKentHundred control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTaxKentHundred As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlKentCommunityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKentCommunityCode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtKentTP3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtKentTP8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKentTP8 As Global.System.Web.UI.WebControls.TextBox
End Class
