'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ucTaxParcelSussex

    '''<summary>
    '''txtTPSussex1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTPSussex6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTPSussex6 As Global.System.Web.UI.WebControls.TextBox
End Class
