'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GeneralNested

    '''<summary>
    '''NestedContentPlaceHolderHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NestedContentPlaceHolderHeader As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''NestedContentPlaceHolderPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NestedContentPlaceHolderPageTitle As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''NestedContentPlaceHolderBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NestedContentPlaceHolderBody As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''NestedContentPlaceHolderJS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NestedContentPlaceHolderJS As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
