'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home
    
    '''<summary>
    '''pnlExternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlExternal As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblHeaderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNewUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewUser As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divuserguide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divuserguide As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hylUserGuide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hylUserGuide As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''pnlInternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInternal As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblHeaderTextInternal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeaderTextInternal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSubmissions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmissions As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnManageUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnManageUser As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSubmitToEPA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitToEPA As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotification As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divExistingPermit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExistingPermit As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblListHeaderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListHeaderText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divCSSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPlanApprovalAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPlanApprovalAgency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtRecdDateFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecdDateFrom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRecdDateTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecdDateTo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPermitNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPermitNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divISSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divISSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtProjectName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectName1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPermitNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPermitNumber1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRecdDateFrom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecdDateFrom1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRecdDateTo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecdDateTo1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divCSNOIList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCSNOIList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lvNOISearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvNOISearch As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''divISNOIList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divISNOIList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lvISNOISearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvISNOISearch As Global.System.Web.UI.WebControls.ListView
End Class
