'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CoPermitteeNOI
    
    '''<summary>
    '''chkPageValidationEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPageValidationEnable As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblNOIID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNOIIDDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIIDDisplay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hfNOISubmissionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNOISubmissionID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hfAfflid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAfflid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblNOIDateReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIDateReceived As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNOIDateReceivedDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNOIDateReceivedDisplay As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ucnaProjectDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaProjectDetails As Global.NoticeOfIntent.ucNameAddressInfoReadOnly
    
    '''<summary>
    '''ucnaOriPermitteeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaOriPermitteeInfo As Global.NoticeOfIntent.ucNameAddressInfoReadOnly
    
    '''<summary>
    '''ucnaCoPermitteeInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucnaCoPermitteeInfo As Global.NoticeOfIntent.ucNameAddressInfo
    
    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEffectiveDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rfvEffectiveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEffectiveDate As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''lblCoPermitteeStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCoPermitteeStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCoPermitteeStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCoPermitteeStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblTerminationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTerminationDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtTerminationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTerminationDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cvTerminationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvTerminationDate As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''cvTerminationDateRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvTerminationDateRequired As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hfSavedSuccessfull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSavedSuccessfull As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
